# Generated by Django 3.2.1 on 2021-05-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cart_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_qnt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
