# Generated by Django 3.2.1 on 2021-05-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cart_product_qnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
