# Generated by Django 3.2.1 on 2021-05-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cart_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_status',
            field=models.BooleanField(default=True),
        ),
    ]
