# Generated by Django 3.2.1 on 2021-05-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('mobile_num', models.IntegerField()),
                ('alternate_mobile_num', models.IntegerField()),
            ],
        ),
    ]
