# Generated by Django 3.2.1 on 2021-05-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alternate_mobile_num',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_num',
            field=models.TextField(max_length=10),
        ),
    ]
