# Generated by Django 3.2.1 on 2021-05-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210505_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='l_name',
        ),
        migrations.AddField(
            model_name='user',
            name='u_name',
            field=models.CharField(default='dasd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='u_password',
            field=models.CharField(default='ds', max_length=100),
            preserve_default=False,
        ),
    ]
