# Generated by Django 3.2.1 on 2021-05-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_brand_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_id',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
